### ISSUE TITLE
Fails on nested topics

### ISSUE THREAD

**Issue by felixduvallet** [OTL/rqt_ez_publisher#17]
Thanks for the great tool.

I found an issue when attempting to publish to a nested topic, for example the following Subscribers:

```
rospy.Subscriber('/some/topic', Float32)
rospy.Subscriber('/some/topic/again', Float32)
rospy.Subscriber('/this/works', Float32)
```

Selecting `/some/topic` works, but `/some/topic/again` produces the following (very frequent) error message:

> [WARN] [WallTime: 1459858994.495491] 'again' is not in list
> [WARN] [WallTime: 1459858994.513921] 'again' is not in list
> [WARN] [WallTime: 1459858994.530778] 'again' is not in list
> [WARN] [WallTime: 1459858994.547622] 'again' is not in list

**Comment by OTL** [comment]
Hi, thank you for giving good feedback!
This is because rqt_ez_publisher supports publishing a part of a topic.
It can publish /some/topic's specific member.
If you input /some/topic/data for rqt_ez_publisher, it will create slider to publish /some/topic's "data" member variable (other members will be initialized by zero).
(Float32 has only one member, so this is the same behavior when you input /some/topic)

/some/topic/again is interpreted as "publish again member of /some/topic" by mistake.

Anyway, if it searches nested topic first, it can be fixed. I'll try to fix it.

**Comment by felixduvallet** [comment]
Ah, I see why that happens. I agree it's worth checking for a nested topic somewhere in `find_topic_name`, but it's also probably just as easy to change the topics on my side (and fix the freezing + repeated message problem). Let me know which you decide!

**Comment by OTL** [comment]
I pushed a change to indigo-devel and jade-devel to fix the issue.
Could you try it?

**Comment by felixduvallet** [comment]
Thanks, this works great!
(FYI, I'm using the sliders for controlling grasps in this [ROS package](https://github.com/felixduvallet/grasp-synergy))
